### ISSUE TITLE
✨ [Feature] 데이터 자동화

### ISSUE THREAD

**Issue by ssu-uky** [wanted-A/GIS-Restaurant#11]
## Description
데이터 자동화

## Todo
- [x] todo1

## 기타 사항
etc...

**Comment by allen9535** [comment]
feature/jeongheon/#11 브랜치에 데이터 수집 및 저장 자동화 코드 업로드 해 보았습니다.

적용 사항은 아래와 같습니다.
1. config/settings.py
    * Celery 및 Celery-Beat 관련 옵션들을 추가했습니다.( 172 ~ 186 라인)
2. config/celery.py
    * Django 프로젝트에서 Celery를 사용할 수 있도록 설정하는 파일을 추가했습니다.
3. config/tasks.py
    * 제가 기존에 작성했던 데이터 수집·전처리·저장하는 코드들을 이 파일로 옮기고, Celery가 인식할 수 있도록 shared_task 데코레이터를 추가했습니다.

테스트 환경은 아래와 같습니다.
* RabbitMQ(Docker 환경, Docker Official Image 사용) / Celery(로컬 환경) / Celery-Beat(로컬 환경)

사용한 명령어는 아래와 같습니다.
* RabbitMQ
  ```
  docker run -p 5672:5672 rabbitmq
  ```
* Celery
  ```
  celery -A config worker -l info --pool=solo
  ```
  ```
  (--pool=solo 옵션의 경우, Windows에서만 발생한다는 Celery 오류를 회피하기 위함이므로 Mac의 경우에는 빼셔도 좋을 것 같습니다.)
  ```
  ```
  참고한 블로그(https://velog.io/@jaewan/Celerywindow%EC%97%90%EC%84%9C-celery-task%EA%B0%80-%EC%8B%A4%ED%96%89%EB%90%98%EC%A7%80-%EC%95%8A%EB%8A%94-%EB%AC%B8%EC%A0%9C)
  ```
* Celery-Beat
  ```
  celery -A config beat -l info
  ```

Crontab의 스케쥴 설정에 도움이 될만한 사이트를 소개합니다. cron 생성기입니다.
```
https://crontab.guru/
```
