### ISSUE TITLE
✨ [Feature] Restaurant List API

### ISSUE THREAD

**Issue by ssu-uky** [wanted-A/GIS-Restaurant#4]
## Description
맛집 목록 조회

## Todo
- [x] 로그인 한 user의 거리를 중심으로 1km / 5km 사이의 음식점 목록 리스트 조회

## 기타 사항
etc...

**Comment by allen9535** [comment]
사용자 위경도를 입력 받아 일정 범위 내의 맛집 목록 반환 기능 생성했습니다!
다만 몇 가지 상의할 사항이 있다 판단해 공유합니다.

1. 두 좌표의 위경도를 통해 거리를 구하는 라이브러리가 이미 있다.
    * 제 경우에는 검색을 통해 haversine 함수라는 수학 공식에 대해서, 그리고 그 공식을 어떻게 Python에서 적용하고 사용할지에 대해 공부했습니다. 그리고 그 내용을 기반으로 get_haversine_distance라는 함수를 만들었습니다. 그런데 이 haversine 함수를 라이브러리로 만들어 업로드 한 것이 있었습니다. PyPI에 등록된 haversine이라는 라이브러리가 그것입니다.
    * 다만 제가 만든 함수와 해당 라이브러리 모두 아주 정확하게 거리를 맞추지는 못합니다. 각각 200 ~ 300m 가량 오차가 있습니다. 또 제가 만든 함수와 해당 라이브러리 간에는 300 ~ 400m 가량 차이가 있습니다.
    * 따라서 직접 만든 함수를 사용하는 것이 좋을지, 기존에 누군가 이미 만들어 둔 라이브러리를 사용하는 것이 좋을지 상의가 필요할 것 같습니다.

2. 사전 필터링에 관하여
    * 관련 내용을 검색하다 보니 사전 필터링을 사용하면 쿼리 속도를 줄일 수 있다는 내용이 있었습니다. 현재 제 코드에서는 모든 음식점 데이터를 받아온 다음 거리를 일일이 비교하게 되어 있는데, 사전에 일정 범위 내의 음식점 데이터를 가져온 다음 거리를 일일이 비교하게 되면 소폭이나마 성능 향상을 도모할 수 있을 것 같습니다.
    * 예를 들어 보자면, 사용자 좌표로 주소를 알아냄(구글 지오코딩 API) -> 해당 주소 범위의 음식점들 가져옴(예. 경기도 과천시의 음식점 전체) -> 거리 비교
    * 다만 저도 아이디어 단계라 정말 가능한지는 잘 모르겠습니다.

3. Restaurant 모델 이름 문제
    * 코드 작성 자체는 금방 끝났는데, 거리 비교 기능들이 제대로 작동하지 않아 헤맸습니다.
    * 원인은 모델명 부분에 있었습니다. data_pipeline.py의 내용들을 tasks.py로 옮기면서 제대로 체크되지 않았던 것 같습니다.
    * restaurants/tasks.py의 47~48 라인인데, REFINE_WGS84_LOGT(경도 데이터)가 latitude(위도)에, REFINE_WGS84_LAT(위도 데이터)가 longitude(경도)에 연결되어 있었습니다. 제가 업로드한 코드에는 수정되어 있으나, 혹시 해당 데이터를 사용해야 한다면 로컬에서 수정한 후 사용하시는 것이 좋을 것 같습니다.

**Comment by kyeon06** [comment]
>     "REFINE_WGS84_LOGT": "latitude",
>     "REFINE_WGS84_LAT": "longitude"

헉 데이터 매칭하는 부분에서 실수가 있었네요 ㅜㅜ 제대로 체크했어야했는데 죄송합니다!
해당 부분은 수정해서 올려주시면 감사하겠습니다!

**Comment by kyeon06** [comment]
사전 필터링에 관하여,
저도 해당 내용에 대해 피드백을 받은 경험이 있었는데요! 아무래도 모든 데이터를 가져와서 비교하는 것 보다 사전에 일정 범위 혹은 일정 데이터만 받아오는 것이 속도가 좀 더 빠르지 않을까 생각합니다. 구현이 가능하다면 사전 필터링을 적용하는 것이 좋을 듯 싶습니다:)

**Comment by kyeon06** [comment]
위경도 거리 계산에 관하여,
```py
import math


def lat_lon_to_km(point_1, point_2):
    lat1 = point_1[1]
    lon1 = point_1[0]
    lat2 = point_2[1]
    lon2 = point_2[0]

    R = 6371 # km
    dLat = math.radians(lat2-lat1)
    dLon = math.radians(lon2-lon1)
    
    lat1 = math.radians(lat1)
    lat2 = math.radians(lat2)

    a = math.sin(dLat/2) * math.sin(dLat/2) + \
        math.sin(dLon/2) * math.sin(dLon/2) * math.cos(lat1) * math.cos(lat2)
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))

    return R * c

point_1 = [
          127.07596008849987,
        37.2040
        ]

point_2 =[
          127.08726833239848,
          37.19497222488765
        ]


distance = lat_lon_to_km(point_1, point_2)
print("거리 (km): " + str(distance))
```

멘토님이 거리계산 하는 코드를 올려주셨었는데 이것도 테스트 해보셨을까요?!

**Comment by allen9535** [comment]
> 위경도 거리 계산에 관하여,
> 
> ```python
> import math
> 
> 
> def lat_lon_to_km(point_1, point_2):
>     lat1 = point_1[1]
>     lon1 = point_1[0]
>     lat2 = point_2[1]
>     lon2 = point_2[0]
> 
>     R = 6371 # km
>     dLat = math.radians(lat2-lat1)
>     dLon = math.radians(lon2-lon1)
>     
>     lat1 = math.radians(lat1)
>     lat2 = math.radians(lat2)
> 
>     a = math.sin(dLat/2) * math.sin(dLat/2) + \
>         math.sin(dLon/2) * math.sin(dLon/2) * math.cos(lat1) * math.cos(lat2)
>     c = 2 * math.atan2(math.sqrt(a), math.sqrt(1-a))
> 
>     return R * c
> 
> point_1 = [
>           127.07596008849987,
>         37.2040
>         ]
> 
> point_2 =[
>           127.08726833239848,
>           37.19497222488765
>         ]
> 
> 
> distance = lat_lon_to_km(point_1, point_2)
> print("거리 (km): " + str(distance))
> ```
> 
> 멘토님이 거리계산 하는 코드를 올려주셨었는데 이것도 테스트 해보셨을까요?!

네! 현재 제가 작성한 코드가 멘토님 제공해주신 코드 기반입니다. 같은 결과가 나오는 수식입니다!

**Comment by kyeon06** [comment]
작성하신 위경도 구하는 로직과 해당 라이브러리에서 계산되는 로직이 차이가 없다면 라이브러리를 사용하는 것이 더 낫지 않을까 생각이 듭니다! 아니면 라이브러리를 사용하면 어떤 식으로 계산되는지 모르니 일단 작성하신 코드 기반으로 구현하는 것도 좋을 듯 싶습니다:)

**Comment by allen9535** [comment]
해당 라이브러리의 문서에 어떤 공식을 사용하는지 명시되어 있지는 않습니다!
여러 편의성 관련 기능들도 포함되어 있는 것 같습니다만, 말씀하신 것처럼 어떤 식으로 작동하는 지 알 수 없으니 기존에 작성한 코드를 사용하는 게 명시적이고 좋을 수 있다는 생각이 듭니다.
그럼 기존 작성한 코드를 사용하는 방향으로 코드 작성하겠습니다!
