### ISSUE TITLE
✨ [Feature] Restaurant Detail API

### ISSUE THREAD

**Issue by ssu-uky** [wanted-A/GIS-Restaurant#5]
## Description
맛집 상세정보 API
- `맛집 모든필드` 를 포함합니다.
- `평가` 상세 리스트도 포함됩니다.
    - (`평가` 는 아래 참조.)
    - 모든 내역을 생성시간 역순(최신순) 으로 반환합니다.
    - 추가 요구사항 없습니다.
## Todo
맛집 상세정보 같은 경우에는 두가지로 분리해서 개발 진행하였습니다.
1. 모든 필드 정보 조회
- `GET api/v1/restaurants/detail/<int:restaurant_id>/`

3. 일부 필요 필드 정보 조회
- `GET api/v1/restaurants/<int:restaurant_id>/`

**Comment by kyeon06** [comment]
맛집 상세정보 같은 경우에는 두가지로 분리해서 개발 진행하였습니다.
1. 모든 필드 정보 조회
2. 일부 필요 필드 정보 조회
